In [140]:
import numpy as np
import pandas as pd
from holoviews.examples.gallery.apps.bokeh.streaming_psutil import callback
from sqlalchemy.dialects.mssql.information_schema import columns

# Import Data

## Single Sample

In [141]:
sample = pd.read_csv('Data/train/305_P/305_COVAREP.csv', header=None)
sample['index'] = sample.index

In [142]:
sample

,0,1,2,3,4,5,6,7,8,9,...,65,66,67,68,69,70,71,72,73,index
0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,0.0,0,0.0,0.0,0.0,0.0,0.0,-0.47603,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
3,0.0,0,0.0,0.0,0.0,0.0,0.0,-0.47896,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
4,0.0,0,0.0,0.0,0.0,0.0,0.0,-0.48177,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170395,0.0,0,0.0,0.0,0.0,0.0,0.0,-0.40631,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,170395
170396,0.0,0,0.0,0.0,0.0,0.0,0.0,-0.37672,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,170396
170397,0.0,0,0.0,0.0,0.0,0.0,0.0,-0.36073,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,170397
170398,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,170398
170399,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,170399

In [143]:
time = pd.read_csv('Data/train/305_P/305_TRANSCRIPT.csv', sep='\t')

In [144]:
time = time[time['speaker'] == 'Ellie']

In [145]:
time

,start_time,stop_time,speaker,value
0,28.655,40.645,Ellie,hi i'm ellie thanks for coming in today i was ...
1,41.355,50.955,Ellie,i'm here to learn about people and would love ...
2,51.625,52.785,Ellie,how are you doing today
4,55.045,55.835,Ellie,that's good
5,56.745,58.445,Ellie,where are you from originally
...,...,...,...,...
394,1656.595,1657.365,Ellie,mhm
398,1666.545,1668.405,Ellie,that sounds like a great situation
400,1671.545,1674.385,Ellie,okay i think i've asked everything i need to
401,1675.035,1677.005,Ellie,thanks for sharing your thoughts with me
403,1678.005,1678.765,Ellie,goodbye

In [146]:
sample.drop(sample[sample['index'].isin(range(int(100*time.loc[0,'start_time'])))].index, inplace = True)
for start,stop in zip(time['start_time'], time['stop_time']):
    sample.drop(sample[sample['index'].isin(range(int(100*start),int(100*stop)))].index, inplace = True)
sample = sample[sample[1] == 1]

In [147]:
sample = sample.drop(columns = ['index'])

In [148]:
sample

,0,1,2,3,4,5,6,7,8,9,...,64,65,66,67,68,69,70,71,72,73
4124,178.5,1,0.002102,0.003991,0.18383,0.002928,0.041721,-0.42975,0.56883,0.58670,...,-0.88182,-0.88583,-0.795640,-0.766990,-0.54423,-0.45790,-0.395090,-0.320970,-0.15968,-0.125150
4125,238.0,1,0.008747,0.045721,-1.46540,0.081416,0.043162,-0.41163,1.01250,0.63697,...,-0.88159,-0.88526,-0.780610,-0.767700,-0.53129,-0.44925,-0.395490,-0.319370,-0.14129,-0.106340
4126,244.5,1,0.068036,0.271380,-10.43800,0.544560,0.046011,-0.40602,1.32330,0.66048,...,-0.88126,-0.88915,-0.762890,-0.765170,-0.52110,-0.43481,-0.394990,-0.317160,-0.13450,-0.081891
4127,251.0,1,0.069171,0.210600,-6.55630,0.586550,0.040959,-0.40170,1.40000,0.63094,...,-0.88617,-0.89190,-0.746020,-0.753610,-0.51612,-0.41672,-0.391320,-0.316370,-0.13005,-0.056660
4128,251.0,1,0.049676,0.171940,-1.20050,0.607450,0.065597,-0.40381,1.77600,0.67415,...,-0.89509,-0.89444,-0.734790,-0.728360,-0.51360,-0.39925,-0.380820,-0.313740,-0.11984,-0.039661
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170390,212.0,1,0.063411,0.168710,-0.54672,0.795250,0.063490,-0.42673,2.31740,0.66893,...,-1.25100,-1.02910,-0.778860,-0.597510,-0.43090,-0.28006,-0.113650,0.108400,0.23330,0.246900
170391,209.0,1,0.056779,0.169750,-17.12000,0.789070,0.078888,-0.42570,2.49650,0.55134,...,-1.25360,-1.03150,-0.798900,-0.613530,-0.41963,-0.24809,-0.093838,0.102570,0.20997,0.239020
170392,206.0,1,0.061566,0.207220,-22.11400,0.592430,0.112120,-0.43093,2.49650,0.55083,...,-1.23870,-1.01860,-0.806230,-0.612900,-0.40638,-0.22794,-0.074448,0.100310,0.19227,0.225250
170393,202.0,1,0.061496,0.216620,-13.98100,0.502860,0.115110,-0.44107,1.53850,0.52187,...,-1.19770,-0.98596,-0.791190,-0.589830,-0.38598,-0.21017,-0.061840,0.099042,0.17980,0.208570
170394,198.0,1,0.000000,0.000000,0.00000,0.000000,0.000000,-0.43254,1.20100,0.53427,...,0.27148,0.66517,-0.038923,0.003008,-0.35989,-0.33750,0.038994,-0.272810,0.27352,0.577550

## DataFrame

In [149]:
train_labels = pd.read_csv('Data/train.csv')
test_labels = pd.read_csv('Data/dev.csv')

In [150]:
df = []
for rank in train_labels['Participant_ID']:
    sample = pd.read_csv(f'Data/train/{rank}_P/{rank}_COVAREP.csv', header=None)
    sample['index'] = sample.index
    time = pd.read_csv(f'Data/train/{rank}_P/{rank}_TRANSCRIPT.csv', sep='\t')
    time = time[time['speaker'] == 'Ellie']
    for start,stop in zip(time['start_time'], time['stop_time']):
        sample.drop(sample[sample['index'].isin(range(int(100*start),int(100*stop)))].index, inplace = True)
    sample = sample[sample[1] == 1]
    df.append(sample.drop(columns = ['index']))

In [151]:
df_test = []
for rank in test_labels['Participant_ID']:
    sample = pd.read_csv(f'Data/test/{rank}_P/{rank}_COVAREP.csv', header=None)
    sample['index'] = sample.index
    time = pd.read_csv(f'Data/test/{rank}_P/{rank}_TRANSCRIPT.csv', sep='\t')
    time = time[time['speaker'] == 'Ellie']
    for start,stop in zip(time['start_time'], time['stop_time']):
        sample.drop(sample[sample['index'].isin(range(int(100*start),int(100*stop)))].index, inplace = True)
    sample = sample[sample[1] == 1]
    df_test.append(sample.drop(columns = ['index']))

In [152]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
scale = pd.concat([sample.iloc[:,[0]] for sample in df])
sc.fit(scale)

StandardScaler()

In [153]:
max_row = 0

In [154]:
for sample in df:
    sample.iloc[:,[0]] = sc.transform(sample.iloc[:,[0]])
    sample.drop(columns=sample.columns[1], inplace = True)
    max_row = max(max_row, sample.shape[0])

In [155]:
for sample in df_test:
    sample.iloc[:,[0]] = sc.transform(sample.iloc[:,[0]])
    sample.drop(columns=sample.columns[1], inplace = True)
    max_row = max(max_row, sample.shape[0])

In [156]:
max_row

84768

In [157]:
df_reduce = []
df_test_reduce = []
for sample in df:
    df_reduce.append(sample.groupby(sample.index//25).mean())
for sample in df_test:
    df_test_reduce.append(sample.groupby(sample.index//25).mean())

In [158]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_train = pad_sequences(df_reduce, maxlen=3400, dtype='float32', padding='post', value=0.0)
X_test = pad_sequences(df_test_reduce, maxlen=3400, dtype='float32', padding='post', value=0.0)

In [159]:
X_train.shape

(107, 3400, 73)

In [160]:
y_train = []
y_test = []
for label in train_labels['PHQ8_Binary']:
    y_train.append(label)
for label in test_labels['PHQ8_Binary']:
    y_test.append(label)
y_train = np.array(y_train)
y_test = np.array(y_test)

In [161]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [162]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Masking

model = Sequential([
    Masking(mask_value=0.0),
    LSTM(64, return_sequences=True),
    Dropout(0.3),
    LSTM(32),
    Dropout(0.3),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [163]:
model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=4,
    validation_split=0.2
)

Epoch 1/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 44s 2s/step - accuracy: 0.6353 - loss: 0.6711 - val_accuracy: 0.9091 - val_loss: 0.5118
Epoch 2/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 42s 2s/step - accuracy: 0.6706 - loss: 0.6220 - val_accuracy: 0.9091 - val_loss: 0.5115
Epoch 3/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.6471 - loss: 0.6266 - val_accuracy: 0.9091 - val_loss: 0.5381
Epoch 4/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.7059 - loss: 0.5832 - val_accuracy: 0.8636 - val_loss: 0.4679
Epoch 5/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.7294 - loss: 0.5186 - val_accuracy: 0.8636 - val_loss: 0.3804
Epoch 6/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 41s 2s/step - accuracy: 0.7529 - loss: 0.4977 - val_accuracy: 0.7727 - val_loss: 0.4633
Epoch 7/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.7529 - loss: 0.5091 - val_accuracy: 0.6364 - val_loss: 0.5537
Epoch 8/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 41s 2s/step - accuracy: 0.7529 - loss: 0.4987 - val_accuracy: 0.5000 - val_loss: 0.7555
Epoch 9/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.7647 - loss: 0.4658 - val_accuracy: 0.6364 - val_loss: 0.5688
Epoch 10/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.7765 - loss: 0.4430 - val_accuracy: 0.7273 - val_loss: 0.4956
Epoch 11/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.8235 - loss: 0.3943 - val_accuracy: 0.7273 - val_loss: 0.5093
Epoch 12/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.8706 - loss: 0.3704 - val_accuracy: 0.7727 - val_loss: 0.5631
Epoch 13/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.8588 - loss: 0.3196 - val_accuracy: 0.7727 - val_loss: 0.5665
Epoch 14/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 41s 2s/step - accuracy: 0.8353 - loss: 0.3517 - val_accuracy: 0.7727 - val_loss: 0.5789
Epoch 15/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.8588 - loss: 0.2883 - val_accuracy: 0.5000 - val_loss: 1.0556
Epoch 16/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 41s 2s/step - accuracy: 0.9176 - loss: 0.2481 - val_accuracy: 0.7273 - val_loss: 0.6882
Epoch 17/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.9176 - loss: 0.2170 - val_accuracy: 0.6364 - val_loss: 0.7987
Epoch 18/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.9059 - loss: 0.2217 - val_accuracy: 0.5909 - val_loss: 0.9073
Epoch 19/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 41s 2s/step - accuracy: 0.9059 - loss: 0.2152 - val_accuracy: 0.6364 - val_loss: 0.8849
Epoch 20/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.8353 - loss: 0.3711 - val_accuracy: 0.8636 - val_loss: 0.5215

In [164]:
pred = model.predict(X_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 564ms/step

In [165]:
pred

array([[0.07502408],
       [0.24695721],
       [0.01151313],
       [0.01379751],
       [0.01687762],
       [0.00472417],
       [0.03805837],
       [0.00502168],
       [0.07338632],
       [0.2422014 ],
       [0.33359015],
       [0.00765987],
       [0.02252035],
       [0.07093928],
       [0.5522272 ],
       [0.23271595],
       [0.15133408],
       [0.06938028],
       [0.6043815 ],
       [0.00406044],
       [0.04000068],
       [0.03290003],
       [0.03770675],
       [0.11903583],
       [0.00532776],
       [0.01547021],
       [0.48243117],
       [0.00830342],
       [0.01294395],
       [0.08882614],
       [0.00332867],
       [0.7048985 ],
       [0.3865104 ],
       [0.39735475],
       [0.15540947]], dtype=float32)

In [190]:
y_pred = [1 if p > 0.5 else 0 for p in pred]

In [191]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[21  2]
 [10  2]]
0.6571428571428571

In [168]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Bidirectional, LSTM, Dense, Dropout, Masking
from tensorflow.keras.callbacks import EarlyStopping

model2 = Sequential([
    Masking(mask_value=0.0),
    LSTM(32, return_sequences=True),
    Dropout(0.3),
    LSTM(16),
    Dropout(0.3),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])
model2.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)
early_stop = EarlyStopping(monitor='val_loss', patience=8, restore_best_weights=True)

In [169]:
model2.fit(
    X_train, y_train,
    epochs=40,
    batch_size=4,
    validation_split=0.2,
    callbacks = [early_stop]
)

Epoch 1/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 44s 2s/step - accuracy: 0.6706 - loss: 0.6657 - val_accuracy: 0.9091 - val_loss: 0.5212
Epoch 2/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.6706 - loss: 0.6336 - val_accuracy: 0.9091 - val_loss: 0.4668
Epoch 3/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.6588 - loss: 0.6244 - val_accuracy: 0.9091 - val_loss: 0.4763
Epoch 4/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.6588 - loss: 0.6100 - val_accuracy: 0.8636 - val_loss: 0.4952
Epoch 5/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.7529 - loss: 0.5762 - val_accuracy: 0.7727 - val_loss: 0.5213
Epoch 6/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.7412 - loss: 0.5391 - val_accuracy: 0.7273 - val_loss: 0.5414
Epoch 7/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.6824 - loss: 0.5579 - val_accuracy: 0.7273 - val_loss: 0.5429
Epoch 8/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.7059 - loss: 0.5316 - val_accuracy: 0.7727 - val_loss: 0.4543
Epoch 9/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.7647 - loss: 0.5145 - val_accuracy: 0.7727 - val_loss: 0.4415
Epoch 10/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.7882 - loss: 0.4811 - val_accuracy: 0.7273 - val_loss: 0.4813
Epoch 11/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.8000 - loss: 0.4250 - val_accuracy: 0.7273 - val_loss: 0.4841
Epoch 12/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.8471 - loss: 0.4132 - val_accuracy: 0.7273 - val_loss: 0.5332
Epoch 13/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.8000 - loss: 0.4483 - val_accuracy: 0.5909 - val_loss: 0.6160
Epoch 14/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.8471 - loss: 0.4005 - val_accuracy: 0.4545 - val_loss: 0.7387
Epoch 15/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.8000 - loss: 0.4967 - val_accuracy: 0.8182 - val_loss: 0.4018
Epoch 16/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.8353 - loss: 0.4162 - val_accuracy: 0.7727 - val_loss: 0.4434
Epoch 17/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.8588 - loss: 0.4295 - val_accuracy: 0.7727 - val_loss: 0.4432
Epoch 18/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.8941 - loss: 0.3685 - val_accuracy: 0.5909 - val_loss: 0.6770
Epoch 19/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 41s 2s/step - accuracy: 0.8706 - loss: 0.3493 - val_accuracy: 0.5909 - val_loss: 0.6792
Epoch 20/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 42s 2s/step - accuracy: 0.9059 - loss: 0.3024 - val_accuracy: 0.5909 - val_loss: 0.7343
Epoch 21/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.9059 - loss: 0.3101 - val_accuracy: 0.6364 - val_loss: 0.6550
Epoch 22/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 42s 2s/step - accuracy: 0.9059 - loss: 0.2960 - val_accuracy: 0.5455 - val_loss: 0.8792
Epoch 23/40
22/22 ━━━━━━━━━━━━━━━━━━━━ 40s 2s/step - accuracy: 0.9176 - loss: 0.3035 - val_accuracy: 0.5455 - val_loss: 0.8303

In [170]:
pred = model2.predict(X_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 556ms/step

In [171]:
pred

array([[0.09896962],
       [0.10762501],
       [0.10617029],
       [0.10627867],
       [0.100113  ],
       [0.09757452],
       [0.13417484],
       [0.6859385 ],
       [0.09696687],
       [0.57987165],
       [0.18733396],
       [0.10457991],
       [0.1265344 ],
       [0.32597873],
       [0.29204774],
       [0.10304146],
       [0.18400212],
       [0.10549928],
       [0.10779977],
       [0.10284223],
       [0.10589466],
       [0.7124176 ],
       [0.10574439],
       [0.09834462],
       [0.10108767],
       [0.10627155],
       [0.11929618],
       [0.09748551],
       [0.10099433],
       [0.1790335 ],
       [0.11487949],
       [0.6630204 ],
       [0.09996081],
       [0.09886796],
       [0.112747  ]], dtype=float32)

In [184]:
y_pred = [1 if p > 0.5 else 0 for p in pred]

In [185]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[21  2]
 [10  2]]
0.6571428571428571