In [1]:
import numpy as np
import pandas as pd

# Import Data

In [2]:
sample = pd.read_csv('Data/train/303_P/303_COVAREP.csv', header=None)

In [3]:
sample['index'] = sample.index // 100

In [4]:
sample

,0,1,2,3,4,5,6,7,8,9,...,65,66,67,68,69,70,71,72,73,index
0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,0.0,0,0.0,0.0,0.0,0.0,0.0,-0.31362,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,0.0,0,0.0,0.0,0.0,0.0,0.0,-0.37019,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,0.0,0,0.0,0.0,0.0,0.0,0.0,-0.37557,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98524,0.0,0,0.0,0.0,0.0,0.0,0.0,-0.33663,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,985
98525,0.0,0,0.0,0.0,0.0,0.0,0.0,-0.32633,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,985
98526,0.0,0,0.0,0.0,0.0,0.0,0.0,-0.31700,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,985
98527,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,985
98528,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,985

In [5]:
sample_1s = sample.groupby(sample['index']).mean()

In [6]:
time = pd.read_csv('Data/train/303_P/303_TRANSCRIPT.csv', sep='\t')

In [7]:
sample_1s['index'] = sample_1s.index

In [8]:
time[time['speaker'] == 'Ellie']

,start_time,stop_time,speaker,value
0,26.276,48.696,Ellie,hi i'm ellie thanks for coming in today i was ...
1,49.256,50.406,Ellie,how are you doing today
3,52.576,54.136,Ellie,i'm great thanks
4,54.816,56.236,Ellie,where are you from originally
6,58.216,58.936,Ellie,really
...,...,...,...,...
183,943.246,944.026,Ellie,yeah
184,945.066,946.936,Ellie,that's so good to hear
186,950.726,953.526,Ellie,okay i think i've asked everything i need to
187,954.266,956.126,Ellie,thanks for sharing your thoughts with me
189,958.656,959.526,Ellie,goodbye

In [10]:
sample_1s.drop(sample_1s[sample_1s['index'].isin(range(int(time.loc[0,'start_time'])))].index, inplace = True)
for start,stop in zip(time['start_time'], time['stop_time']):
    sample_1s.drop(sample_1s[sample_1s['index'].isin(range(int(start),int(stop)))].index, inplace = True)

In [11]:
sample_1s

,0,1,2,3,4,5,6,7,8,9,...,65,66,67,68,69,70,71,72,73,index
index,,,,,,,,,,,,,,,,,,,,,
48,252.520000,0.14,0.057711,0.145250,0.419823,0.286930,0.093852,-0.361145,1.523840,0.547035,...,-0.968559,-0.772763,-0.578405,-0.443500,-0.299512,-0.199227,-0.145498,-0.057824,-0.040410,48
51,224.615000,0.76,0.123949,0.368020,7.151440,0.233691,0.125199,-0.321982,1.500579,0.632184,...,-0.857182,-0.721192,-0.612121,-0.397878,-0.248278,-0.125295,-0.094832,-0.015038,0.062762,51
57,203.380000,0.48,0.149994,0.447072,11.124739,0.343923,0.111608,-0.380384,1.690592,0.609808,...,-0.918174,-0.781415,-0.673908,-0.500658,-0.336855,-0.254198,-0.096714,0.021706,0.081672,57
58,256.995000,0.09,0.078765,0.202859,6.979940,0.141191,0.144488,-0.359557,1.389682,0.524719,...,-0.927511,-0.722539,-0.538682,-0.367579,-0.242306,-0.142486,-0.069203,-0.017974,0.009791,58
59,230.235000,0.11,0.040512,0.099758,3.490139,0.054333,0.146420,-0.359673,1.479667,0.530953,...,-0.881924,-0.784034,-0.637926,-0.495377,-0.399626,-0.302055,-0.228322,-0.173228,-0.110864,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
981,264.210000,0.03,0.000000,0.000000,0.000000,0.000000,0.114385,-0.298765,1.451852,0.538023,...,-1.000354,-0.769189,-0.593206,-0.412323,-0.254574,-0.164766,-0.066311,0.005937,0.037879,981
982,248.440000,0.67,0.109254,0.313883,3.615422,0.286568,0.130710,-0.313267,1.486024,0.568337,...,-0.937528,-0.757179,-0.547067,-0.362571,-0.207346,-0.055852,0.062836,0.086139,0.119720,982
983,234.590000,0.39,0.112989,0.336753,7.566124,0.234171,0.124443,-0.356993,1.577240,0.562730,...,-1.015033,-0.810267,-0.582194,-0.393156,-0.204505,-0.054677,0.020909,0.073515,0.099754,983
984,249.925000,0.06,0.001820,0.005082,0.140465,0.003196,0.057786,-0.299902,1.445152,0.535184,...,-0.861617,-0.734748,-0.637833,-0.512211,-0.408962,-0.368730,-0.277992,-0.214763,-0.129110,984
985,208.862069,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,-0.283965,1.231560,0.415089,...,-0.716782,-0.599262,-0.460243,-0.341626,-0.249019,-0.178927,-0.139599,-0.121112,-0.099167,985