In [1]:
import pandas as pd
import numpy as np

In [2]:
au = pd.read_csv('Data/train/303_P/303_CLNF_AUs.txt')
gaze = pd.read_csv('Data/train/303_P/303_CLNF_gaze.txt')
pose = pd.read_csv('Data/train/303_P/303_CLNF_pose.txt')

In [3]:
au

,frame,timestamp,confidence,success,AU01_r,AU02_r,AU04_r,AU05_r,AU06_r,AU09_r,...,AU17_r,AU20_r,AU25_r,AU26_r,AU04_c,AU12_c,AU15_c,AU23_c,AU28_c,AU45_c
0,1,0.000000,0.981368,1,0.659856,0.0,0.000000,0.000000,0.00000,0.604604,...,0.897072,0.000000,1.537020,0.0,0,0,0,1,0,0
1,2,0.033333,0.980735,1,0.845040,0.0,0.592602,0.545399,0.00000,0.000000,...,0.991509,0.555872,1.145810,0.0,0,0,0,1,0,0
2,3,0.066667,0.980477,1,0.797575,0.0,0.000000,0.672369,0.00000,0.000000,...,0.960490,0.000000,1.383310,0.0,0,0,0,1,0,0
3,4,0.100000,0.980439,1,0.926512,0.0,0.000000,0.723597,0.00000,0.643866,...,0.935476,0.000000,1.100450,0.0,0,0,0,1,0,0
4,5,0.133333,0.980438,1,0.926970,0.0,0.000000,0.695910,0.00000,0.524106,...,0.907883,0.000000,1.190010,0.0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29560,29561,985.333000,0.967921,1,0.000000,0.0,0.642406,0.000000,1.33843,0.000000,...,0.000000,0.000000,0.000000,0.0,0,1,0,0,0,0
29561,29562,985.367000,0.969969,1,0.000000,0.0,0.639222,0.000000,1.32095,0.000000,...,0.000000,0.000000,0.842536,0.0,0,1,0,0,0,0
29562,29563,985.400000,0.965266,1,0.000000,0.0,0.729308,0.000000,1.29807,0.000000,...,0.000000,0.000000,0.862451,0.0,0,1,0,0,0,0
29563,29564,985.433000,0.968920,1,0.000000,0.0,0.000000,0.000000,1.31108,0.000000,...,0.000000,0.000000,0.856023,0.0,0,1,0,0,0,0
29564,29565,985.467000,0.969575,1,0.000000,0.0,0.000000,0.000000,1.32638,0.000000,...,0.000000,0.000000,0.628544,0.0,0,1,0,0,0,0

In [4]:
gaze

,frame,timestamp,confidence,success,x_0,y_0,z_0,x_1,y_1,z_1,x_h0,y_h0,z_h0,x_h1,y_h1,z_h1
0,1,0.000000,0.981368,1,0.050079,0.098449,-0.993881,-0.032585,0.083760,-0.995953,-0.006358,0.070951,-0.997460,-0.089732,0.061428,-0.994070
1,2,0.033333,0.980735,1,0.050203,0.085346,-0.995086,-0.019518,0.075966,-0.996919,-0.010188,0.053971,-0.998490,-0.080333,0.049126,-0.995557
2,3,0.066667,0.980477,1,0.052620,0.086090,-0.994897,-0.019757,0.076738,-0.996855,-0.008544,0.052292,-0.998595,-0.081343,0.047745,-0.995542
3,4,0.100000,0.980439,1,0.052326,0.083745,-0.995112,-0.019646,0.077822,-0.996774,-0.009415,0.049591,-0.998725,-0.081569,0.048484,-0.995488
4,5,0.133333,0.980438,1,0.052759,0.082940,-0.995157,-0.019311,0.077857,-0.996778,-0.009226,0.048539,-0.998779,-0.081419,0.048296,-0.995509
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29560,29561,985.333000,0.967921,1,0.184218,0.131270,-0.974080,-0.012636,0.227838,-0.973617,0.217872,0.173395,-0.960451,0.042179,0.304284,-0.951647
29561,29562,985.367000,0.969969,1,0.193961,0.131686,-0.972131,-0.031147,0.227860,-0.973196,0.227842,0.178320,-0.957230,0.024455,0.314297,-0.949010
29562,29563,985.400000,0.965266,1,0.143323,0.137703,-0.980049,-0.026247,0.212818,-0.976739,0.179650,0.187833,-0.965632,0.026831,0.292518,-0.955884
29563,29564,985.433000,0.968920,1,0.170599,0.138035,-0.975624,-0.024091,0.208002,-0.977832,0.205406,0.185113,-0.961011,0.026913,0.289642,-0.956757
29564,29565,985.467000,0.969575,1,0.191953,0.138951,-0.971518,-0.002051,0.208753,-0.977966,0.226624,0.182870,-0.956661,0.049177,0.288056,-0.956350

In [5]:
pose

,frame,timestamp,confidence,success,Tx,Ty,Tz,Rx,Ry,Rz
0,1,0.000000,0.981368,1,39.62630,57.3311,753.640,-0.041053,0.052339,-0.062683
1,2,0.033333,0.980735,1,39.65600,57.3148,752.933,-0.044771,0.055062,-0.065109
2,3,0.066667,0.980477,1,39.64500,57.3013,752.489,-0.047086,0.055927,-0.066365
3,4,0.100000,0.980439,1,39.65690,57.2967,752.521,-0.047474,0.056318,-0.066882
4,5,0.133333,0.980438,1,39.65120,57.2988,752.471,-0.047693,0.056502,-0.067129
...,...,...,...,...,...,...,...,...,...,...
29560,29561,985.333000,0.967921,1,8.43542,52.9587,751.104,0.070617,-0.011738,-0.185679
29561,29562,985.367000,0.969969,1,8.58863,53.2171,751.766,0.077660,-0.012571,-0.186575
29562,29563,985.400000,0.965266,1,8.40747,52.1946,751.628,0.070809,-0.012012,-0.186141
29563,29564,985.433000,0.968920,1,8.61792,52.1844,750.285,0.073179,-0.011592,-0.185073
29564,29565,985.467000,0.969575,1,8.68257,53.0316,752.103,0.074946,-0.011664,-0.188426

In [6]:
sample = au.merge(gaze).merge(pose)

In [7]:
sample

,frame,timestamp,confidence,success,AU01_r,AU02_r,AU04_r,AU05_r,AU06_r,AU09_r,...,z_h0,x_h1,y_h1,z_h1,Tx,Ty,Tz,Rx,Ry,Rz
0,1,0.000000,0.981368,1,0.659856,0.0,0.000000,0.000000,0.00000,0.604604,...,-0.997460,-0.089732,0.061428,-0.994070,39.62630,57.3311,753.640,-0.041053,0.052339,-0.062683
1,2,0.033333,0.980735,1,0.845040,0.0,0.592602,0.545399,0.00000,0.000000,...,-0.998490,-0.080333,0.049126,-0.995557,39.65600,57.3148,752.933,-0.044771,0.055062,-0.065109
2,3,0.066667,0.980477,1,0.797575,0.0,0.000000,0.672369,0.00000,0.000000,...,-0.998595,-0.081343,0.047745,-0.995542,39.64500,57.3013,752.489,-0.047086,0.055927,-0.066365
3,4,0.100000,0.980439,1,0.926512,0.0,0.000000,0.723597,0.00000,0.643866,...,-0.998725,-0.081569,0.048484,-0.995488,39.65690,57.2967,752.521,-0.047474,0.056318,-0.066882
4,5,0.133333,0.980438,1,0.926970,0.0,0.000000,0.695910,0.00000,0.524106,...,-0.998779,-0.081419,0.048296,-0.995509,39.65120,57.2988,752.471,-0.047693,0.056502,-0.067129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29273,29561,985.333000,0.967921,1,0.000000,0.0,0.642406,0.000000,1.33843,0.000000,...,-0.960451,0.042179,0.304284,-0.951647,8.43542,52.9587,751.104,0.070617,-0.011738,-0.185679
29274,29562,985.367000,0.969969,1,0.000000,0.0,0.639222,0.000000,1.32095,0.000000,...,-0.957230,0.024455,0.314297,-0.949010,8.58863,53.2171,751.766,0.077660,-0.012571,-0.186575
29275,29563,985.400000,0.965266,1,0.000000,0.0,0.729308,0.000000,1.29807,0.000000,...,-0.965632,0.026831,0.292518,-0.955884,8.40747,52.1946,751.628,0.070809,-0.012012,-0.186141
29276,29564,985.433000,0.968920,1,0.000000,0.0,0.000000,0.000000,1.31108,0.000000,...,-0.961011,0.026913,0.289642,-0.956757,8.61792,52.1844,750.285,0.073179,-0.011592,-0.185073
29277,29565,985.467000,0.969575,1,0.000000,0.0,0.000000,0.000000,1.32638,0.000000,...,-0.956661,0.049177,0.288056,-0.956350,8.68257,53.0316,752.103,0.074946,-0.011664,-0.188426

In [8]:
sample = sample[sample[' confidence'] > 0.75]
sample = sample[sample[' success'] == 1]

In [9]:
sample.drop(columns = [ 'frame', ' timestamp', ' confidence', ' success'], inplace=True)

In [10]:
sample.shape[0]

29069

In [11]:
train_labels = pd.read_csv('Data/train.csv')
test_labels = pd.read_csv('Data/dev.csv')

In [12]:
big = 0
train = []
for add in train_labels['Participant_ID']:
    au = pd.read_csv(f'Data/train/{add}_P/{add}_CLNF_AUs.txt')
    gaze = pd.read_csv(f'Data/train/{add}_P/{add}_CLNF_gaze.txt')
    pose = pd.read_csv(f'Data/train/{add}_P/{add}_CLNF_pose.txt')
    sample = au.merge(gaze).merge(pose)
    sample = sample[sample[' confidence'] > 0.75]
    sample = sample[sample[' success'] == 1]
    sample.drop(columns=[ 'frame', ' timestamp', ' confidence', ' success'], inplace=True)
    big = max(big, sample.shape[0])
    train.append(sample)

In [13]:
test = []
for add in test_labels['Participant_ID']:
    au = pd.read_csv(f'Data/test/{add}_P/{add}_CLNF_AUs.txt')
    gaze = pd.read_csv(f'Data/test/{add}_P/{add}_CLNF_gaze.txt')
    pose = pd.read_csv(f'Data/test/{add}_P/{add}_CLNF_pose.txt')
    sample = au.merge(gaze).merge(pose)
    sample = sample[sample[' confidence'] > 0.75]
    sample = sample[sample[' success'] == 1]
    sample.drop(columns=[ 'frame', ' timestamp', ' confidence', ' success'], inplace=True)
    big = max(big, sample.shape[0])
    test.append(sample)

In [14]:
big

52256

In [15]:
train[0]

,AU01_r,AU02_r,AU04_r,AU05_r,AU06_r,AU09_r,AU10_r,AU12_r,AU14_r,AU15_r,...,z_h0,x_h1,y_h1,z_h1,Tx,Ty,Tz,Rx,Ry,Rz
0,0.659856,0.0,0.000000,0.000000,0.00000,0.604604,0.00000,0.00000,0.000000,0.0,...,-0.997460,-0.089732,0.061428,-0.994070,39.62630,57.3311,753.640,-0.041053,0.052339,-0.062683
1,0.845040,0.0,0.592602,0.545399,0.00000,0.000000,0.00000,0.00000,0.000000,0.0,...,-0.998490,-0.080333,0.049126,-0.995557,39.65600,57.3148,752.933,-0.044771,0.055062,-0.065109
2,0.797575,0.0,0.000000,0.672369,0.00000,0.000000,0.00000,0.00000,0.000000,0.0,...,-0.998595,-0.081343,0.047745,-0.995542,39.64500,57.3013,752.489,-0.047086,0.055927,-0.066365
3,0.926512,0.0,0.000000,0.723597,0.00000,0.643866,0.00000,0.00000,0.000000,0.0,...,-0.998725,-0.081569,0.048484,-0.995488,39.65690,57.2967,752.521,-0.047474,0.056318,-0.066882
4,0.926970,0.0,0.000000,0.695910,0.00000,0.524106,0.00000,0.00000,0.000000,0.0,...,-0.998779,-0.081419,0.048296,-0.995509,39.65120,57.2988,752.471,-0.047693,0.056502,-0.067129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29273,0.000000,0.0,0.642406,0.000000,1.33843,0.000000,1.29970,1.89108,1.293120,0.0,...,-0.960451,0.042179,0.304284,-0.951647,8.43542,52.9587,751.104,0.070617,-0.011738,-0.185679
29274,0.000000,0.0,0.639222,0.000000,1.32095,0.000000,1.23894,1.86012,1.046280,0.0,...,-0.957230,0.024455,0.314297,-0.949010,8.58863,53.2171,751.766,0.077660,-0.012571,-0.186575
29275,0.000000,0.0,0.729308,0.000000,1.29807,0.000000,1.24742,1.86747,0.837904,0.0,...,-0.965632,0.026831,0.292518,-0.955884,8.40747,52.1946,751.628,0.070809,-0.012012,-0.186141
29276,0.000000,0.0,0.000000,0.000000,1.31108,0.000000,1.21114,1.88289,0.884394,0.0,...,-0.961011,0.026913,0.289642,-0.956757,8.61792,52.1844,750.285,0.073179,-0.011592,-0.185073
29277,0.000000,0.0,0.000000,0.000000,1.32638,0.000000,1.19272,2.07720,0.891385,0.0,...,-0.956661,0.049177,0.288056,-0.956350,8.68257,53.0316,752.103,0.074946,-0.011664,-0.188426

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(pd.concat(train, axis=0, ignore_index=True))

StandardScaler()

In [17]:
for i in range(len(train)):
    train[i] = sc.transform(train[i])

In [18]:
for i in range(len(test)):
    test[i] = sc.transform(test[i])

In [19]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

X_train = pad_sequences(train, maxlen=big, padding='post', value=0.0, dtype='float32')
X_test = pad_sequences(test, maxlen=big, padding='post', value=0.0, dtype='float32')

In [20]:
y_train = np.array([label for label in train_labels['PHQ8_Binary']])
y_test = np.array([label for label in test_labels['PHQ8_Binary']])

In [21]:
y_train.shape

(107,)

In [22]:
X_train.shape

(107, 52256, 38)

In [23]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Masking, Dropout, LSTM

model = Sequential([
    Masking(mask_value=0.0),
    LSTM(64, input_shape=(X_train.shape[1], X_train.shape[2])),
    Dropout(0.3),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

D:\Softwears\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [24]:
from tensorflow.keras.callbacks import EarlyStopping
stop = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

In [25]:
model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=4,
    validation_split=0.2,
    callbacks = [stop]
)

Epoch 1/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 277s 13s/step - accuracy: 0.6000 - loss: 0.6733 - val_accuracy: 0.9091 - val_loss: 0.5418
Epoch 2/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 303s 14s/step - accuracy: 0.7176 - loss: 0.5759 - val_accuracy: 0.9091 - val_loss: 0.5154
Epoch 3/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 324s 15s/step - accuracy: 0.7059 - loss: 0.5222 - val_accuracy: 0.9091 - val_loss: 0.4981
Epoch 4/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 327s 15s/step - accuracy: 0.8118 - loss: 0.4690 - val_accuracy: 0.8636 - val_loss: 0.4755
Epoch 5/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 334s 15s/step - accuracy: 0.8588 - loss: 0.4103 - val_accuracy: 0.9091 - val_loss: 0.4801
Epoch 6/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 334s 15s/step - accuracy: 0.8941 - loss: 0.3437 - val_accuracy: 0.8636 - val_loss: 0.4622
Epoch 7/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 334s 15s/step - accuracy: 0.9176 - loss: 0.2954 - val_accuracy: 0.8182 - val_loss: 0.4763
Epoch 8/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 334s 15s/step - accuracy: 0.9412 - loss: 0.2355 - val_accuracy: 0.8182 - val_loss: 0.4549
Epoch 9/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 338s 15s/step - accuracy: 0.9529 - loss: 0.1883 - val_accuracy: 0.7273 - val_loss: 0.5321
Epoch 10/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 342s 16s/step - accuracy: 0.9882 - loss: 0.1641 - val_accuracy: 0.7273 - val_loss: 0.4372
Epoch 11/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 337s 15s/step - accuracy: 0.9882 - loss: 0.1187 - val_accuracy: 0.7273 - val_loss: 0.4671
Epoch 12/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 340s 15s/step - accuracy: 1.0000 - loss: 0.0806 - val_accuracy: 0.7273 - val_loss: 0.5072
Epoch 13/20
22/22 ━━━━━━━━━━━━━━━━━━━━ 347s 16s/step - accuracy: 1.0000 - loss: 0.0635 - val_accuracy: 0.7273 - val_loss: 0.5171

In [27]:
pred = model.predict(X_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 12s 2s/step

In [50]:
y_pred = [1 if p > 0.3 else 0 for p in pred]

In [51]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[14  9]
 [ 1 11]]
0.7142857142857143